In [1]:
import numpy as np;
print(np.__version__)

1.21.5


In [4]:
arr = np.arange(1,17)

In [5]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [6]:
a = arr%2!=0

In [7]:
print(a)

[ True False  True False  True False  True False  True False  True False
  True False  True False]


In [8]:
print(arr[a])

[ 1  3  5  7  9 11 13 15]


In [13]:
new_arr = arr%2 == 0

In [14]:
new_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True])

In [15]:
arr[new_arr]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:
new_arr = arr.reshape(4,4)

In [25]:
arr.mean()

8.5

In [26]:
np.transpose(new_arr)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [27]:
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
new_arr.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [29]:
np.sqrt(new_arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [30]:
sum(np.sqrt(new_arr))

array([ 9.84161925, 10.76763835, 11.56741026, 12.29252874])

In [32]:
sum(sum(new_arr))

136

In [33]:
new_arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [34]:
new_arr[3:5, 2:5]

array([[15, 16]])