# Basic Operations in Arrays

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40])
b = np.arange(1,5)

In [3]:
a

array([10, 20, 30, 40])

In [4]:
b

array([1, 2, 3, 4])

In [5]:
a+b

array([11, 22, 33, 44])

In [6]:
a - b

array([ 9, 18, 27, 36])

In [7]:
a * b

array([ 10,  40,  90, 160])

In [8]:
a ** b

array([     10,     400,   27000, 2560000], dtype=int32)

In [9]:
#masking
a>15

array([False,  True,  True,  True])

In [10]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [11]:
np.log10(b)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [12]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

#### Matrix Product

In [13]:
A = np.random.randint(0,5, (3,4))
B = np.random.randint(0,5, (4,2))

In [14]:
A

array([[3, 1, 4, 2],
       [4, 1, 4, 3],
       [3, 0, 3, 4]])

In [15]:
B

array([[4, 1],
       [0, 1],
       [0, 0],
       [3, 1]])

In [17]:
np.dot(A,B)

array([[18,  6],
       [25,  8],
       [24,  7]])

# More Operations on Arrays

In [19]:
A = np.arange(0,24)

In [22]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
A = A.reshape(6,4)

In [24]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [26]:
np.sum(A)

276

In [27]:
np.max(A)

23

In [28]:
np.min(A)

0

In [29]:
np.mean(A)

11.5

In [30]:
np.std(A)

6.922186552431729

In [31]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
np.sum(A, axis=0)

array([60, 66, 72, 78])

In [33]:
np.sum(A, axis=1)

array([ 6, 22, 38, 54, 70, 86])