# Broadcasting
    - First Rule of numpy : 2 Arrays can performs operations only when they have same shapes
    - broadcasting let two arrays of different shapes to do some operations.
        - A small array will repeat itself, and convert to the same shape as of another array.

In [8]:
A = np.random.randint(0,10, size=(3,3))
a=np.array([[1,2,3]])

In [9]:
A

array([[9, 5, 7],
       [9, 1, 2],
       [9, 0, 8]])

In [10]:
a

array([[1, 2, 3]])

In [11]:
print(A.shape, a.shape)

(3, 3) (1, 3)


In [12]:
A + a

array([[10,  7, 10],
       [10,  3,  5],
       [10,  2, 11]])

In [13]:
a.T

array([[1],
       [2],
       [3]])

In [14]:
A + a.T

array([[10,  6,  8],
       [11,  3,  4],
       [12,  3, 11]])

In [15]:
A + 4

array([[13,  9, 11],
       [13,  5,  6],
       [13,  4, 12]])