# Indexing in Array

In [2]:
import numpy as np

In [17]:
np.random.randint(10,100)

44

In [34]:
new_arr = np.random.randint(10,100,(5,4))

In [35]:
new_arr

array([[63, 66, 75, 26],
       [34, 75, 13, 36],
       [39, 44, 72, 67],
       [13, 20, 80, 15],
       [88, 46, 65, 96]])

In [36]:
#first row
new_arr[0]

array([63, 66, 75, 26])

In [37]:
new_arr[-2]

array([13, 20, 80, 15])

In [38]:
new_arr[0,0]

63

In [39]:
new_arr[-1,-1]

96

In [41]:
new_arr[:,2]

array([75, 13, 72, 80, 65])

## Array Slicing

In [44]:
# arr[start_row_idx : end_row_idx + 1, start_col_idx : end_col_idx + 1]

In [43]:
new_arr[2:5, 1:4]

array([[44, 72, 67],
       [20, 80, 15],
       [46, 65, 96]])

In [45]:
new_arr[2:5, 1:]

array([[44, 72, 67],
       [20, 80, 15],
       [46, 65, 96]])

In [47]:
#third column only
new_arr[:, 2]

array([75, 13, 72, 80, 65])

In [48]:
new_arr[0,0] = 0

In [49]:
new_arr

array([[ 0, 66, 75, 26],
       [34, 75, 13, 36],
       [39, 44, 72, 67],
       [13, 20, 80, 15],
       [88, 46, 65, 96]])

In [52]:
#masking
mask = new_arr > 10
mask

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
np.sum(mask)

19

In [55]:
#get all values greated than 10
new_arr[mask]

array([66, 75, 26, 34, 75, 13, 36, 39, 44, 72, 67, 13, 20, 80, 15, 88, 46,
       65, 96])

In [56]:
new_arr

array([[ 0, 66, 75, 26],
       [34, 75, 13, 36],
       [39, 44, 72, 67],
       [13, 20, 80, 15],
       [88, 46, 65, 96]])

In [57]:
new_arr[2: , 2:] = 0

In [58]:
new_arr

array([[ 0, 66, 75, 26],
       [34, 75, 13, 36],
       [39, 44,  0,  0],
       [13, 20,  0,  0],
       [88, 46,  0,  0]])