# Numpy Basics

array : Fundamental element in numpy is homogeneous array. Numpy arrays can be 1D, 2D, 3D ...nD

    - Different ways to create np array
        1. np.array()
        2. np.arange()

In [1]:
import numpy as np

In [2]:
l = [1,5,8,9]

np_arr = np.array(l)

In [3]:
np_arr

array([1, 5, 8, 9])

In [4]:
type(np_arr)

numpy.ndarray

In [5]:
np_arr.ndim

1

In [6]:
#important
np_arr.shape

(4,)

### Another way to create np array

In [7]:
new_arr = np.arange(3,11)

In [8]:
new_arr

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
lst_2d = [ [1,2,3],
           [4,5,6],
           [7,8,9] ]

In [10]:
arr_2d = np.array(lst_2d)

In [11]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr_2d.ndim

2

In [13]:
arr_2d.shape

(3, 3)